<?php

/**
 * Implements hook_views_api().
 */
function commerce_backoffice_content_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'commerce_backoffice') . '/includes/views',
  );
}

/**
 * Implements hook_form_alter().
 */
function commerce_backoffice_content_form_alter(&$form, &$form_state, $form_id) {
  // Alter the exposed filters for the content view.
  if (isset($form['submit']['#id']) && $form['submit']['#id'] == 'edit-submit-commerce-backoffice-content') {
    $form['non_product_display_node_type']['#attributes'] = array('data-placeholder' => array(t('All content types')));
    $form['status']['#options']['All'] = t('All statuses');
    $form['combine']['#attributes'] = array('placeholder' => array(t('Search by title or author')));
  }
  // Alter the exposed filters for the comments view.
  if (isset($form['submit']['#id']) && $form['submit']['#id'] == 'edit-submit-commerce-backoffice-comments') {
    $form['combine']['#attributes'] = array('placeholder' => array(t('Search by subject or author')));
  }
}

/**
 * Implements hook_autoload_info().
 */
function commerce_backoffice_content_autoload_info() {
  return array(
    'commerce_backoffice_content_filter_node_type' => 'includes/views/handlers/commerce_backoffice_content_filter_node_type.inc',
    'commerce_backoffice_handler_field_node_operations' => 'includes/views/handlers/commerce_backoffice_handler_field_node_operations.inc',
    'commerce_backoffice_handler_field_term_entity_tid' => 'includes/views/handlers/commerce_backoffice_handler_field_term_entity_tid.inc',
    'commerce_backoffice_handler_filter_term_node_tid' => 'includes/views/handlers/commerce_backoffice_handler_filter_term_node_tid.inc',
    'commerce_backoffice_order_handler_field_order_operations' => 'includes/views/handlers/commerce_backoffice_order_handler_field_order_operations.inc',
    'commerce_backoffice_product_handler_field_product_quick_edit_form' => 'includes/views/handlers/commerce_backoffice_product_handler_field_product_quick_edit_form.inc',
    'commerce_backoffice_content_plugin_display_system' => 'includes/views/plugins/commerce_backoffice_content_plugin_display_system.inc',
  );
}
